name: PluginHealth
main: com.KAMKEEL.PluginHealth.PluginHealth
version: 1.0
author: KAMKEEL
commands:
    maxhealth:
        description: reload config

permissions:
    maxhealth.reload:
        description: reload config
